name: Publish cookie-banner
on:
  push:
    tags: ['v*-cookie-banner']

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: true
    name: Publish cookie-banner
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build cookie-banner
        run: |
          yarn install
          yarn build

      - name: Publish cookie-banner
        working-directory: ./packages/cookie-banner
        run: |
          yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        id: publish-cookie-banner
